# Generated by Django 4.1.5 on 2023-01-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workersprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
