# Generated by Django 4.1.5 on 2023-02-01 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_hodprofile_dob_alter_workersprofile_dob'),
        ('task', '0003_task_done_task_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='hod',
            new_name='createdBy',
        ),
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hodprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.workersprofile')),
            ],
        ),
    ]
