# Generated by Django 4.1.5 on 2023-02-03 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_hod_department_createdby_workertask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workersdepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='workersdepartment',
            name='worker',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dscription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='WorkersDepartment',
        ),
    ]
