# Generated by Django 4.1.5 on 2023-02-03 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_done_alter_task_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
