# Generated by Django 4.1.5 on 2023-02-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=1000000),
        ),
    ]
