# Generated by Django 4.1.5 on 2023-02-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_hodprofile_dob_alter_workersprofile_dob'),
        ('task', '0008_alter_task_createdat_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hodprofile'),
        ),
    ]
