# Generated by Django 4.1.5 on 2023-02-03 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_hodprofile_dob_alter_workersprofile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('createdBy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hodprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkersDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.workersprofile')),
            ],
        ),
    ]
